version: "3.8"
services:
  hfm:
    build: .
    environment:
      - HFM_CONF_PATH=/data/
    ports:
      - "9002:9002"
    volumes:
      - type: bind
        source: ./data
        target: /data
    restart: unless-stopped