---
image:
  repository: ghcr.io/danielskowronski/homefloormap
  tag: "v0.3.0a3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9002
ingress:
  enabled: true
  hosts:
    - host: homefloormap.local
      paths:
        - /
  tls:
    - hosts:
        - homefloormap.local
      secretName: homefloormap-tls

existingSecretName: hfm
